### ISSUE TITLE
Help! Exception NoSuchMethodError

### ISSUE THREAD

**Issue by arnaudot** [LordAkkarin/Beacon#27]
On Manjaro Linux, Java 8, when trying to run the jar.
`Exception in thread "main" java.lang.NoSuchMethodError: java.lang.Class.getPackageName()Ljava/lang/String;
	at tv.dotstart.beacon.core.util.VersionMetadata.getId(VersionMetadata.kt:45)
	at tv.dotstart.beacon.core.util.VersionMetadata.<init>(VersionMetadata.kt:57)
	at tv.dotstart.beacon.ui.BeaconUiMetadata.<init>(BeaconUiMetadata.kt:26)
	at tv.dotstart.beacon.ui.BeaconUiMetadata.<clinit>(BeaconUiMetadata.kt:26)
	at tv.dotstart.beacon.ui.BeaconCli.<clinit>(Beacon.kt:134)
	at tv.dotstart.beacon.ui.BeaconKt.main(Beacon.kt:273)`

Do I need some packages that I'm missing?

**Comment by dotStart** [comment]
Your Java installation is too old. Beacon 2.4 requires Java 9 while Beacon 3.x even requires Java 11 hence the error related to [Class#getPackageName](https://docs.oracle.com/javase/9/docs/api/java/lang/Class.html#getPackageName--) (which was introduced in Java 9).

Generally, I currently recommend sticking to the LTS versions of Java when running Beacon as there have been various issues reported due to the changes in architecture the Java APIs are currently going through. They're the only versions I actively validate when releasing a new version. The latest validated version is Java 11 (as 17 has just been released a few weeks ago).

That being said: Version 2.4 was lacking a check for the minimum required Java version within the application itself as the target audience are mostly Windows users (The assumption is that somebody who runs Linux will probably prefer to configure their router themselves). Version 3.x changes that fact but its checks have not been updated to reflect the Java 11 requirement yet (as it is still an Alpha release, that's somewhat acceptable).
